apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Bisoyi624/argo-cd-test1.git    # Replace it with your forked repo
    targetRevision: main
    path: argocdproj/service
  destination:
    server: https://172.31.12.223:33894   # Replace with your Cluster Url, To get run: `argocd cluster list`
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
